spring:
  profiles:
    active: dev
  application:
    name: huoban-backend
  # DataSource配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huoban
    username: root
    password: ******
  # session失效时间（分钟）
  session:
    timeout: 86400 #两个月
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 0


server:
  port: 8080
  servlet:
    context-path: /api


# mybatis-plus的配置
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  type-aliases-package: com.forty.huoban.domain
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长

